#!/usr/bin/env node
/**
 * validate_runtime.mjs — Phase 3 Runtime Standardization
 *
 * Validates GPT provider runtime data files against the provider_contracts schemas.
 *
 * Reads:
 *   - providers/gpt-web-api/data/jobs.json      → validates images.generations jobs against image-task.schema.json
 *   - providers/gpt-web-api/data/media.json    → validates media records against artifact-record.schema.json
 *
 * Normalization:
 *   - jobs.json image-gen: result[] items → ImageTask.outputs[] shape (output_path→local_path, mime_type→mime)
 *   - media.json: legacy "media" format → ArtifactRecord format (output_path→local_path, object:media→artifact)
 *
 * Exit codes:
 *   0  — all validations pass
 *   1  — validation errors found (unnormalized or genuinely invalid)
 *   2  — file not found or parse error
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import addFormats from "ajv-formats";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const SCHEMAS_DIR = path.join(__dirname, "schemas");
const DATA_DIR = path.join(__dirname, "../../providers/gpt-web-api/data");

const ajv = new Ajv({ allErrors: true, strict: false, validateSchema: false });
addFormats(ajv);

// Pre-load and register all schemas by their $id (Ajv v8: must pre-register before compile)
const schemaByFile = {};
const schemaFiles = [
  "image-task.schema.json",
  "artifact-record.schema.json",
  "artifact-output.schema.json",
];
for (const file of schemaFiles) {
  const raw = await fs.readFile(path.join(SCHEMAS_DIR, file), "utf8");
  schemaByFile[file] = JSON.parse(raw);
}
for (const [, schema] of Object.entries(schemaByFile)) {
  if (schema.$id) ajv.addSchema(schema);
}

const imageTaskValidator = ajv.compile(schemaByFile["image-task.schema.json"]);
const artifactRecordValidator = ajv.compile(schemaByFile["artifact-record.schema.json"]);

let exitCode = 0;

// ---------------------------------------------------------------------------
// jobs.json → ImageTask normalization
// ---------------------------------------------------------------------------

/**
 * Normalize a jobs.json image-generation job to ImageTask shape.
 * See packages/provider_contracts/schemas/ARTIFACT_MAPPING.md
 *
 * Current jobs.json gaps (not errors — Phase 4+ write path issues):
 *   - artifact_id: not stored in jobs.json (generated by MediaStore on artifact write)
 *   - width/height: not extracted from image in jobs.json
 *   - sha256: not computed in jobs.json
 *   - account_id / profile_lock: not tracked per-job in current implementation
 */
function normalizeJobToImageTask(job) {
  const isImageGen = job.type === "images.generations";
  const outputs = [];

  if (isImageGen && Array.isArray(job.result)) {
    for (const item of job.result) {
      outputs.push({
        artifact_id: item.artifact_id || null,
        url: item.image_url || item.output_path || "",
        mime: item.mime_type || "",
        width: item.width || null,
        height: item.height || null,
        sha256: item.sha256 || null,
      });
    }
  }

  return {
    contract_version: "1.0.0",
    id: job.id,
    provider: job.metadata?.provider || null,
    model: job.metadata?.model || null,
    status: job.status === "succeeded" ? "succeeded"
         : job.status === "failed"    ? "failed"
         : job.status === "running"   ? "running"
         : job.status === "queued"    ? "queued"
         : job.status,
    prompt: Array.isArray(job.result)
      ? (job.result[0]?.prompt || job.metadata?.prompt || "")
      : (job.metadata?.prompt || ""),
    n: job.metadata?.n || 1,
    input_images: [],
    outputs,
    attempts: job.error ? 1 : 0,
    account_id: null,
    profile_lock: null,
    proxy_id: null,
    created_at: job.created_at,
    updated_at: job.updated_at,
    started_at: job.started_at,
    completed_at: job.finished_at,
    error: job.error ? {
      code: job.error.name || "Error",
      message: job.error.message || String(job.error),
      retriable: false,
    } : null,
    metadata: {
      object: job.object,
      type: job.type,
      conversation_url: Array.isArray(job.result) ? job.result[0]?.conversation_url : null,
    },
  };
}

// ---------------------------------------------------------------------------
// media.json → ArtifactRecord normalization
// ---------------------------------------------------------------------------

/**
 * Normalize a legacy media.json record to ArtifactRecord shape.
 * The existing media.json uses:
 *   - object: "media"       → should be "artifact"
 *   - output_path           → should be local_path
 *   - missing contract_version
 *   - missing width/height/sha256 (not extracted at write time)
 *
 * After normalization, the record should pass artifact-record.schema.json validation.
 */
function normalizeMediaToArtifactRecord(record) {
  return {
    contract_version: "wcapi.artifact.v1",
    id: record.id,
    object: "artifact",
    provider: record.provider,
    kind: record.kind,
    model: record.model,
    prompt: record.prompt || "",
    mime_type: record.mime_type || "",
    created_at: record.created_at,
    local_path: record.output_path || record.local_path || "",
    url: record.url || "",
    source_url: record.source_url || "",
    metadata: {
      ...(record.metadata || {}),
      // width/height were not stored in legacy media records — note as missing
      _legacy_record: true,
    },
  };
}

// ---------------------------------------------------------------------------
// Validation runners
// ---------------------------------------------------------------------------

async function validateJobs() {
  const jobsPath = path.join(DATA_DIR, "jobs.json");
  let raw;
  try {
    raw = await fs.readFile(jobsPath, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") {
      console.error(`ERROR: jobs.json not found at ${jobsPath}`);
      process.exit(2);
    }
    throw err;
  }

  let data;
  try {
    data = JSON.parse(raw);
  } catch {
    console.error("ERROR: jobs.json is not valid JSON");
    process.exit(2);
  }

  const jobs = data.jobs || [];
  const imageGenJobs = jobs.filter(j => j.type === "images.generations");

  console.log(`\n=== jobs.json ===`);
  console.log(`Total jobs: ${jobs.length}  |  images.generations: ${imageGenJobs.length}`);

  if (imageGenJobs.length === 0) {
    console.log("No images.generations jobs — nothing to validate.");
    return;
  }

  let valid = 0;
  let gaps = 0;

  for (const job of imageGenJobs) {
    const normalized = normalizeJobToImageTask(job);
    const ok = imageTaskValidator(normalized);

    if (ok) {
      valid++;
      console.log(`  [PASS]  ${job.id}  status=${job.status}`);
    } else {
      exitCode = 1;
      gaps++;
      console.error(`  [GAP]   ${job.id}  status=${job.status}`);

      // Classify errors: null fields for missing write-path data vs genuine errors
      for (const err of imageTaskValidator.errors || []) {
        const instancePath = err.instancePath.replace(/^\//, "") || "(root)";
        const isKnownGap = (
          // artifact_id not yet assigned in jobs.json (generated at MediaStore artifact time)
          (err.keyword === "type" && err.params.type === "string" &&
           (instancePath.includes("artifact_id") || instancePath.includes("sha256")) &&
           normalized.outputs.some(o => o.artifact_id === null || o.sha256 === null)) ||
          // width/height not extracted from image
          (err.keyword === "type" && err.params.type === "integer" &&
           instancePath.includes("width") && normalized.outputs.some(o => o.width === null)) ||
          (err.keyword === "type" && err.params.type === "integer" &&
           instancePath.includes("height") && normalized.outputs.some(o => o.height === null))
        );

        if (isKnownGap) {
          console.error(`    KNOWN GAP: ${instancePath}: ${err.message}`);
          console.error(`      → field not in jobs.json write path; added by MediaStore/Phase 4+`);
        } else {
          console.error(`    ${instancePath}: ${err.message}`);
        }
      }
    }
  }

  console.log(`\n  image-task schema: ${valid} fully valid, ${gaps} with known gaps (expected)`);
  if (gaps > 0) {
    console.log(`  NOTE: Gaps are expected — jobs.json does not store artifact_id, width, height, sha256.`);
    console.log(`  Fix: update job_queue.mjs or MediaStore write path in Phase 4+ to populate these fields.`);
  }
}

async function validateMedia() {
  const mediaPath = path.join(DATA_DIR, "media.json");
  let raw;
  try {
    raw = await fs.readFile(mediaPath, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") {
      console.error(`ERROR: media.json not found at ${mediaPath}`);
      process.exit(2);
    }
    throw err;
  }

  let data;
  try {
    data = JSON.parse(raw);
  } catch {
    console.error("ERROR: media.json is not valid JSON");
    process.exit(2);
  }

  const records = Object.values(data);
  console.log(`\n=== media.json ===`);
  console.log(`Total records: ${records.length}`);

  if (records.length === 0) {
    console.log("No media records — nothing to validate.");
    return;
  }

  // Check if any records are in legacy "media" format (pre-schema)
  const legacyRecords = records.filter(r => r.object === "media");
  if (legacyRecords.length > 0) {
    console.log(`  Legacy "media" format records: ${legacyRecords.length} (will be normalized before validation)`);
  }

  let valid = 0;
  let normalized = 0;
  let invalid = 0;

  for (const record of records) {
    // Normalize legacy format before validation
    const normalizedRecord = record.object === "media"
      ? normalizeMediaToArtifactRecord(record)
      : record;

    if (record.object === "media") normalized++;

    const validator = artifactRecordValidator;
    const ok = validator(normalizedRecord);

    if (ok) {
      valid++;
      const tag = record.object === "media" ? " legacy→normalized" : "";
      console.log(`  [PASS]  ${record.id}  kind=${record.kind}  provider=${record.provider}${tag}`);
    } else {
      exitCode = 1;
      invalid++;
      console.error(`  [FAIL]  ${record.id}`);

      // Distinguish normalization gaps from genuine errors
      const hasOutputPathGap = record.object === "media" && !record.local_path && record.output_path;
      for (const err of validator.errors || []) {
        const instancePath = err.instancePath.replace(/^\//, "") || "(root)";
        const isNormalizationGap = (
          hasOutputPathGap &&
          (instancePath === "local_path" || instancePath === "object" || instancePath === "contract_version")
        );
        if (isNormalizationGap) {
          console.error(`    NORM GAP (expected for legacy records): ${instancePath}: ${err.message}`);
        } else {
          console.error(`    ${instancePath}: ${err.message}`);
        }
      }
    }
  }

  console.log(`\n  artifact-record schema: ${valid} valid, ${invalid} invalid`);
  if (normalized > 0) {
    console.log(`  ${normalized} legacy "media" records normalized to "artifact" format`);
  }
  if (invalid > 0) {
    console.log(`  NOTE: Failures after normalization indicate records that need migration.`);
    console.log(`  Fix: re-write records via MediaStore to get correct schema (Phase 4+).`);
  }
}

await validateJobs();
await validateMedia();

console.log(`\n=== Summary ===`);
if (exitCode === 0) {
  console.log("All validations passed.");
} else {
  console.log("Validation gaps/errors found — see above for details.");
  console.log("Gaps in jobs.json/media.json are expected at Phase 3 — they require write-path");
  console.log("updates in Phase 4+ (JobQueue / MediaStore). This script validates alignment");
  console.log("and documents what needs to change.");
}
process.exit(exitCode);
