import fs from "node:fs/promises";
import path from "node:path";

export const ARTIFACT_CONTRACT_VERSION = "wcapi.artifact.v1";

function createArtifactId(prefix = "artifact") {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

function normalizeKind(kind = "") {
  const value = String(kind || "").trim().toLowerCase();
  if (["image", "audio", "video", "document", "binary"].includes(value)) {
    return value;
  }
  return "unknown";
}

export function normalizeImageModelBucket(model = "") {
  const value = String(model || "").trim();
  const normalized = value.toLowerCase();

  if (!value) return "other";
  if (normalized === "chatgpt-images") return "chatgpt-images";
  if (normalized === "gpt-image-2") return "gpt-image-2";
  if (normalized.startsWith("imagen-")) return "imagen-*";
  if (normalized.includes("stable-diffusion")) return "stable-diffusion";
  if (normalized.includes("flux")) return "flux";
  if (normalized.includes("seedream")) return "seedream";
  if (normalized.includes("recraft")) return "recraft";
  if (normalized.includes("midjourney")) return "midjourney";

  return value;
}

export function groupImageArtifactsByModel(records = []) {
  const groups = new Map();

  for (const record of records) {
    if (normalizeKind(record?.kind) !== "image") continue;
    const bucket = normalizeImageModelBucket(record?.model);
    if (!groups.has(bucket)) groups.set(bucket, []);
    groups.get(bucket).push(record);
  }

  return [...groups.entries()]
    .map(([bucket, items]) => ({
      bucket,
      items: items.slice().sort((a, b) => {
        const left = Number(b?.created_at || 0);
        const right = Number(a?.created_at || 0);
        return left - right;
      }),
    }))
    .sort((a, b) => a.bucket.localeCompare(b.bucket));
}

export function renderImageModelIndex({ records = [], sourcePaths = [] } = {}) {
  const groups = groupImageArtifactsByModel(records);
  const lines = [
    "# Image Model Index",
    "",
    "This file is generated from persisted artifact indexes.",
    "",
    "Purpose:",
    "",
    "- group generated images by image-generation model",
    "- preserve existing runtime `local_path` references",
    "- give future cleanup/migration work one stable source of truth",
    "",
    "Rules:",
    "",
    "- Do not manually move files already referenced by `providers/*/data/media.json` unless the persisted index is rewritten in the same change.",
    "- New review, export, and archive work should group by `model` first.",
    "- Provider remains secondary metadata; model is the primary organization axis.",
    "",
    "## Current Inventory",
    "",
    "Snapshot source:",
    "",
  ];

  if (sourcePaths.length > 0) {
    for (const sourcePath of sourcePaths) {
      lines.push(`- \`${sourcePath}\``);
    }
  } else {
    lines.push("- _No artifact indexes discovered_");
  }

  if (groups.length === 0) {
    lines.push("", "No persisted image artifacts found.");
  } else {
    for (const group of groups) {
      lines.push("", `### \`${group.bucket}\``, "", `Count: \`${group.items.length}\``, "", "| Artifact ID | Provider | Model | File | Size | SHA-256 |", "|-------------|----------|-------|------|------|---------|");
      for (const item of group.items) {
        const width = item?.metadata?.width;
        const height = item?.metadata?.height;
        const size = width && height ? `${width}x${height}` : "unknown";
        lines.push(`| \`${item.id || ""}\` | \`${item.provider || ""}\` | \`${item.model || ""}\` | \`${item.local_path || ""}\` | \`${size}\` | \`${item?.metadata?.sha256 || ""}\` |`);
      }
    }
  }

  lines.push(
    "",
    "## Planned Model Buckets",
    "",
    "Use these buckets whenever more image providers/models are added:",
    "",
    "- `chatgpt-images`",
    "- `gpt-image-2`",
    "- `imagen-*`",
    "- `stable-diffusion`",
    "- `flux`",
    "- `seedream`",
    "- `recraft`",
    "- `midjourney`",
    "- `other`",
    "",
    "## Current Gap",
    "",
    groups.length === 0
      ? "No persisted image artifacts are currently indexed."
      : "This index only reflects artifacts already persisted by workers. New providers should append their own image artifacts through the same ArtifactRecord path.",
    "",
    "_Generated by `node packages/provider_artifacts/build_image_model_index.mjs`._",
    ""
  );

  return `${lines.join("\n")}`;
}

export function buildArtifactRecord({
  provider,
  kind,
  model,
  prompt = "",
  localPath,
  publicUrl = "",
  sourceUrl = "",
  mimeType = "",
  metadata = {},
  idPrefix = "artifact",
  id = "",
}) {
  if (!provider) throw new Error("provider is required");
  if (!model) throw new Error("model is required");
  if (!localPath) throw new Error("localPath is required");

  return {
    contract_version: ARTIFACT_CONTRACT_VERSION,
    id: id || createArtifactId(idPrefix),
    object: "artifact",
    provider,
    kind: normalizeKind(kind),
    model,
    prompt,
    mime_type: mimeType,
    created_at: Math.floor(Date.now() / 1000),
    local_path: localPath,
    url: publicUrl,
    source_url: sourceUrl,
    metadata: { ...metadata },
  };
}

export function createArtifactStore({ indexPath, publicBaseUrl = "", publicPathPrefix = "/generated" }) {
  async function readIndex() {
    try {
      return JSON.parse(await fs.readFile(indexPath, "utf8"));
    } catch (error) {
      if (error.code === "ENOENT") return {};
      throw error;
    }
  }

  async function writeIndex(index) {
    await fs.mkdir(path.dirname(indexPath), { recursive: true });
    await fs.writeFile(indexPath, JSON.stringify(index, null, 2));
  }

  async function recordArtifact({
    provider,
    kind,
    model,
    prompt = "",
    localPath,
    sourceUrl = "",
    mimeType = "",
    metadata = {},
    idPrefix = "artifact",
    id = "",
  }) {
    const filename = path.basename(localPath);
    const base = String(publicBaseUrl || "").replace(/\/+$/, "");
    const prefix = String(publicPathPrefix || "/generated").replace(/\/+$/, "");
    const publicUrl = base ? `${base}${prefix}/${filename}` : "";
    const record = buildArtifactRecord({
      provider,
      kind,
      model,
      prompt,
      localPath,
      publicUrl,
      sourceUrl,
      mimeType,
      metadata,
      idPrefix,
      id,
    });
    const index = await readIndex();
    index[record.id] = record;
    await writeIndex(index);
    return record;
  }

  async function listArtifacts() {
    const index = await readIndex();
    return Object.values(index).sort((a, b) => (b.created_at || 0) - (a.created_at || 0));
  }

  return {
    readIndex,
    writeIndex,
    recordArtifact,
    listArtifacts,
  };
}
